# Generated by Django 4.2.7 on 2025-10-02 11:25

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название бота')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('bot_type', models.CharField(choices=[('completion', 'Completion'), ('chat', 'Chat')], default='chat', max_length=20, verbose_name='Тип бота')),
                ('gpt_model', models.CharField(default='gpt-3.5-turbo', max_length=50, verbose_name='Модель GPT')),
                ('temperature', models.FloatField(default=0.7, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(2.0)], verbose_name='Температура')),
                ('max_tokens', models.IntegerField(default=1000, verbose_name='Максимальное количество токенов')),
                ('system_prompt', models.TextField(blank=True, verbose_name='Системный промпт')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Создатель')),
            ],
            options={
                'verbose_name': 'Бот',
                'verbose_name_plural': 'Боты',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название сценария')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenarios', to='bots.bot', verbose_name='Бот')),
            ],
            options={
                'verbose_name': 'Сценарий',
                'verbose_name_plural': 'Сценарии',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название шага')),
                ('step_type', models.CharField(choices=[('message', 'Сообщение'), ('question', 'Вопрос'), ('condition', 'Условие'), ('api_call', 'API вызов')], default='message', max_length=20, verbose_name='Тип шага')),
                ('content', models.JSONField(verbose_name='Содержание шага')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('next_step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_steps', to='bots.step', verbose_name='Следующий шаг')),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='bots.scenario', verbose_name='Сценарий')),
            ],
            options={
                'verbose_name': 'Шаг',
                'verbose_name_plural': 'Шаги',
                'ordering': ['scenario', 'order'],
            },
        ),
        migrations.AddField(
            model_name='scenario',
            name='initial_step',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initial_scenarios', to='bots.step', verbose_name='Начальный шаг'),
        ),
        migrations.CreateModel(
            name='BotExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_session', models.CharField(max_length=100, verbose_name='Сессия пользователя')),
                ('conversation_history', models.JSONField(default=list, verbose_name='История разговора')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Завершено')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bots.bot', verbose_name='Бот')),
                ('current_step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bots.step', verbose_name='Текущий шаг')),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bots.scenario', verbose_name='Сценарий')),
            ],
            options={
                'verbose_name': 'Выполнение бота',
                'verbose_name_plural': 'Выполнения ботов',
                'ordering': ['-created_at'],
            },
        ),
    ]
